---

# Main tasks file for elasticsearch role

- name: Check if elasticsearch is installed
  stat:
    path: "{{ item.home~'/elasticsearch-'~item.version }}"
  register: esdir
  with_items: "{{ elasticsearch_instances }}"
  when: item.version is defined
  tags: [elasticsearch]

- name: Download and Extract elasticsearch
  unarchive:
    src: "{{ elasticsearch_baseurl~'/'~item.item.version~'/elasticsearch-'~item.item.version~'.tar.gz' }}"
    dest: "{{ item.item.home }}"
    owner: "{{ item.item.owner }}"
    group: "{{ item.item.group }}"
    mode: "0750"
    copy: "no"
  with_items: "{{ esdir.results }}"
  when: item.item.version is defined and not item.stat.exists
  tags: [elasticsearch]

- name: Fix permissions
  file:
    path: "{{ item.home~'/elasticsearch-'~item.version }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: yes
  with_items: "{{ elasticsearch_instances }}"
  when: item.version is defined
  tags: [elasticsearch]

- name: Make sure elasticsearch paths exist
  file:
    path: "{{ item[0].home~'/'~item[1] }}"
    state: directory
    owner: "{{ item[0].owner }}"
    group: "{{ item[0].group }}"
    mode: "0755"
  with_nested: 
    - "{{ elasticsearch_instances }}"
    - ['bin', 'data', 'work', 'logs', 'plugins', 'scripts']
  when: item[0].version is defined
  tags: [elasticsearch]

- name: Push elasticsearch config
  template:
    src: elasticsearch.yml.j2
    dest: "{{ item.home~'/elasticsearch-'~item.version~'/config/elasticsearch.yml' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items: "{{ elasticsearch_instances }}"
  when: item.version is defined
  tags: [elasticsearch]

- name: Push elasticsearch env file
  template:
    src: dot.es-env.j2
    dest: "{{ item.home~'/.es-env' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0640"
  with_items: "{{ elasticsearch_instances }}"
  when: item.version is defined
  tags: [elasticsearch]

- name: Push elasticsearch startup script
  template:
    src: els.j2
    dest: "{{ item.home~'/bin/els' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0554"
  with_items: "{{ elasticsearch_instances }}"
  when: item.version is defined
  tags: [elasticsearch]

- name: Install plugins
  elasticsearch_plugin:
    name: "{{ item.1.name }}"
    state: "{{ item.1.state|default('present') }}"
    plugin_bin: "{{ item.0.home~'/elasticsearch-'~item.0.version~'/bin/plugin' }}"
    plugin_dir: "{{ item.0.home~'/plugins/' }}"
  with_subelements:
    - "{{ elasticsearch_instances }}"
    - plugins
  when: item.0.version is defined
  tags: [elasticsearch]
